### ISSUE TITLE
Problems on Windows 11

### ISSUE THREAD

**Issue by ProcessControl-AFV** [konradsikorski/RdpProtocolHandler#12]
When install I have this message:

```
RDP Protocol Handler installed
WARNING: Do not move this file '' to other location, otherwise handler will not work. If you change the location run installation process again.
Press any key to close...
```
Is normal that file is empty?

Also, when entering rdp:// I have the error "Application not found"

Content of **HKEY_CLASSES_ROOT\RDP**:

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\RDP]
@="rdp:Remote Desktop Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\RDP\DefaultIcon]
@="C:\\Windows\\System32\\mstsc.exe"

[HKEY_CLASSES_ROOT\RDP\shell]

[HKEY_CLASSES_ROOT\RDP\shell\open]

[HKEY_CLASSES_ROOT\RDP\shell\open\command]
@="\"\" \"%1\""
```

Thanks!!

**Comment by vuchl** [comment]
I had the same problems too and fixed it by changing the command setting in regedit.

```reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\RDP]
@="rdp:Remote Desktop Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\RDP\DefaultIcon]
@="C:\\Windows\\System32\\mstsc.exe"

[HKEY_CLASSES_ROOT\RDP\shell]

[HKEY_CLASSES_ROOT\RDP\shell\open]

[HKEY_CLASSES_ROOT\RDP\shell\open\command]
@="\"C:\Program Files\RdpProtocolHandler\RdpProtocolHandler.exe\" \"%1\""
```

The change depends on the location of the RdpProtocolHandler.exe file of course. 
![grafik](https://github.com/konradsikorski/RdpProtocolHandler/assets/4921147/882b93cd-447d-4acc-a2ae-e0834043366b)

It looks like this now. Seems like the Insaller in not correctly detecting the current working directory upon install.

**Comment by ProcessControl-AFV** [comment]
> I had the same problems too and fixed it by changing the command setting in regedit.
> 
> ```reg
> Windows Registry Editor Version 5.00
> 
> [HKEY_CLASSES_ROOT\RDP]
> @="rdp:Remote Desktop Protocol"
> "URL Protocol"=""
> 
> [HKEY_CLASSES_ROOT\RDP\DefaultIcon]
> @="C:\\Windows\\System32\\mstsc.exe"
> 
> [HKEY_CLASSES_ROOT\RDP\shell]
> 
> [HKEY_CLASSES_ROOT\RDP\shell\open]
> 
> [HKEY_CLASSES_ROOT\RDP\shell\open\command]
> @="\"C:\Program Files\RdpProtocolHandler\RdpProtocolHandler.exe\" \"%1\""
> ```
> 
> The change depends on the location of the RdpProtocolHandler.exe file of course. ![grafik](https://user-images.githubusercontent.com/4921147/267282522-882b93cd-447d-4acc-a2ae-e0834043366b.png)
> 
> It looks like this now. Seems like the Insaller in not correctly detecting the current working directory upon install.


Thanks, works!

**Comment by konradsikorski** [comment]
thank you i have fixed the problem in the latest version
